"""Create decision and snapshot history

Revision ID: 06a3d5d47f52
Revises: 07f25f04f69d
Create Date: 2026-08-04 14:24:13.097724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '06a3d5d47f52'
down_revision: Union[str, Sequence[str], None] = '07f25f04f69d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=50), nullable=False),
    sa.Column('decision_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('trigger', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('requested_by', sa.String(length=150), nullable=True),
    sa.Column('approved_by', sa.String(length=150), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('committed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('change_set', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('simulation_result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisions_approved_by'), 'decisions', ['approved_by'], unique=False)
    op.create_index(op.f('ix_decisions_decision_type'), 'decisions', ['decision_type'], unique=False)
    op.create_index(op.f('ix_decisions_project_id'), 'decisions', ['project_id'], unique=False)
    op.create_index(op.f('ix_decisions_status'), 'decisions', ['status'], unique=False)
    op.create_table('decision_changes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=100), nullable=False),
    sa.Column('target_id', sa.String(length=150), nullable=True),
    sa.Column('before_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('decision_id', 'sequence', name='uq_decision_changes_decision_sequence')
    )
    op.create_index(op.f('ix_decision_changes_change_type'), 'decision_changes', ['change_type'], unique=False)
    op.create_index(op.f('ix_decision_changes_decision_id'), 'decision_changes', ['decision_id'], unique=False)
    op.create_index('ix_decision_changes_target', 'decision_changes', ['target_type', 'target_id'], unique=False)
    op.create_table('project_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=50), nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('snapshot_type', sa.String(length=50), nullable=False),
    sa.Column('phase', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('approved_by', sa.String(length=150), nullable=True),
    sa.Column('project_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('project_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('calculated_plan', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('planner_version', sa.String(length=100), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'version', name='uq_project_snapshots_project_version')
    )
    op.create_index(op.f('ix_project_snapshots_decision_id'), 'project_snapshots', ['decision_id'], unique=False)
    op.create_index('ix_project_snapshots_project_created', 'project_snapshots', ['project_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_project_snapshots_project_id'), 'project_snapshots', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_snapshots_snapshot_type'), 'project_snapshots', ['snapshot_type'], unique=False)
    op.create_table('snapshot_plan_activities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=50), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('installation_no', sa.String(length=50), nullable=True),
    sa.Column('task_type', sa.String(length=100), nullable=False),
    sa.Column('team_id', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('quantities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['project_snapshots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'sequence', name='uq_snapshot_plan_activities_snapshot_sequence')
    )
    op.create_index(op.f('ix_snapshot_plan_activities_end_date'), 'snapshot_plan_activities', ['end_date'], unique=False)
    op.create_index(op.f('ix_snapshot_plan_activities_installation_no'), 'snapshot_plan_activities', ['installation_no'], unique=False)
    op.create_index(op.f('ix_snapshot_plan_activities_project_id'), 'snapshot_plan_activities', ['project_id'], unique=False)
    op.create_index('ix_snapshot_plan_activities_project_task', 'snapshot_plan_activities', ['project_id', 'task_type'], unique=False)
    op.create_index(op.f('ix_snapshot_plan_activities_snapshot_id'), 'snapshot_plan_activities', ['snapshot_id'], unique=False)
    op.create_index(op.f('ix_snapshot_plan_activities_start_date'), 'snapshot_plan_activities', ['start_date'], unique=False)
    op.create_index(op.f('ix_snapshot_plan_activities_task_type'), 'snapshot_plan_activities', ['task_type'], unique=False)
    op.create_index('ix_snapshot_plan_activities_team_dates', 'snapshot_plan_activities', ['team_id', 'start_date', 'end_date'], unique=False)
    op.create_index(op.f('ix_snapshot_plan_activities_team_id'), 'snapshot_plan_activities', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_snapshot_plan_activities_team_id'), table_name='snapshot_plan_activities')
    op.drop_index('ix_snapshot_plan_activities_team_dates', table_name='snapshot_plan_activities')
    op.drop_index(op.f('ix_snapshot_plan_activities_task_type'), table_name='snapshot_plan_activities')
    op.drop_index(op.f('ix_snapshot_plan_activities_start_date'), table_name='snapshot_plan_activities')
    op.drop_index(op.f('ix_snapshot_plan_activities_snapshot_id'), table_name='snapshot_plan_activities')
    op.drop_index('ix_snapshot_plan_activities_project_task', table_name='snapshot_plan_activities')
    op.drop_index(op.f('ix_snapshot_plan_activities_project_id'), table_name='snapshot_plan_activities')
    op.drop_index(op.f('ix_snapshot_plan_activities_installation_no'), table_name='snapshot_plan_activities')
    op.drop_index(op.f('ix_snapshot_plan_activities_end_date'), table_name='snapshot_plan_activities')
    op.drop_table('snapshot_plan_activities')
    op.drop_index(op.f('ix_project_snapshots_snapshot_type'), table_name='project_snapshots')
    op.drop_index(op.f('ix_project_snapshots_project_id'), table_name='project_snapshots')
    op.drop_index('ix_project_snapshots_project_created', table_name='project_snapshots')
    op.drop_index(op.f('ix_project_snapshots_decision_id'), table_name='project_snapshots')
    op.drop_table('project_snapshots')
    op.drop_index('ix_decision_changes_target', table_name='decision_changes')
    op.drop_index(op.f('ix_decision_changes_decision_id'), table_name='decision_changes')
    op.drop_index(op.f('ix_decision_changes_change_type'), table_name='decision_changes')
    op.drop_table('decision_changes')
    op.drop_index(op.f('ix_decisions_status'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_project_id'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_decision_type'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_approved_by'), table_name='decisions')
    op.drop_table('decisions')
    # ### end Alembic commands ###
