"""add deviations

Revision ID: 079d0dec83f7
Revises: 629c7c97ccd7
Create Date: 2026-09-10 08:53:58.258790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '079d0dec83f7'
down_revision: Union[str, Sequence[str], None] = '629c7c97ccd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deviations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=50), nullable=False),
    sa.Column('deviation_number', sa.String(length=50), nullable=False),
    sa.Column('installation_id', sa.Integer(), nullable=True),
    sa.Column('bottom_manhole_id', sa.Integer(), nullable=True),
    sa.Column('top_manhole_id', sa.Integer(), nullable=True),
    sa.Column('dimension_mm', sa.Integer(), nullable=True),
    sa.Column('deviation_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reported_date', sa.Date(), nullable=True),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('completed_by', sa.String(length=150), nullable=True),
    sa.Column('approved_date', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bottom_manhole_id'], ['manholes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['installation_id'], ['installations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['top_manhole_id'], ['manholes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'deviation_number', name='uq_deviations_project_number')
    )
    op.create_index(op.f('ix_deviations_bottom_manhole_id'), 'deviations', ['bottom_manhole_id'], unique=False)
    op.create_index(op.f('ix_deviations_installation_id'), 'deviations', ['installation_id'], unique=False)
    op.create_index('ix_deviations_project_approved', 'deviations', ['project_id', 'approved_date'], unique=False)
    op.create_index('ix_deviations_project_completed', 'deviations', ['project_id', 'completed_date'], unique=False)
    op.create_index(op.f('ix_deviations_project_id'), 'deviations', ['project_id'], unique=False)
    op.create_index(op.f('ix_deviations_source_reference'), 'deviations', ['source_reference'], unique=False)
    op.create_index(op.f('ix_deviations_top_manhole_id'), 'deviations', ['top_manhole_id'], unique=False)
    op.create_index('ix_deviations_type', 'deviations', ['deviation_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_deviations_type', table_name='deviations')
    op.drop_index(op.f('ix_deviations_top_manhole_id'), table_name='deviations')
    op.drop_index(op.f('ix_deviations_source_reference'), table_name='deviations')
    op.drop_index(op.f('ix_deviations_project_id'), table_name='deviations')
    op.drop_index('ix_deviations_project_completed', table_name='deviations')
    op.drop_index('ix_deviations_project_approved', table_name='deviations')
    op.drop_index(op.f('ix_deviations_installation_id'), table_name='deviations')
    op.drop_index(op.f('ix_deviations_bottom_manhole_id'), table_name='deviations')
    op.drop_table('deviations')
    # ### end Alembic commands ###
