"""Create installation progress and stretches

Revision ID: 07f25f04f69d
Revises: d64ff2356fa4
Create Date: 2026-08-04 12:53:35.104428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '07f25f04f69d'
down_revision: Union[str, Sequence[str], None] = 'd64ff2356fa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('installation_progress',
    sa.Column('installation_id', sa.Integer(), nullable=False),
    sa.Column('opmaaling', sa.Float(), nullable=True),
    sa.Column('forarbejde', sa.Float(), nullable=True),
    sa.Column('stikopmaaling', sa.Float(), nullable=True),
    sa.Column('hovedledning', sa.Float(), nullable=True),
    sa.Column('stikaabning', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['installation_id'], ['installations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('installation_id')
    )
    op.create_table('stretches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('installation_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('from_brond', sa.String(length=100), nullable=False),
    sa.Column('to_brond', sa.String(length=100), nullable=False),
    sa.Column('length_m', sa.Float(), nullable=False),
    sa.Column('dimension', sa.String(length=50), nullable=False),
    sa.Column('material', sa.String(length=50), nullable=False),
    sa.Column('stik', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['installation_id'], ['installations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('installation_id', 'sequence', name='uq_stretches_installation_sequence')
    )
    op.create_index('ix_stretches_from_to_brond', 'stretches', ['from_brond', 'to_brond'], unique=False)
    op.create_index(op.f('ix_stretches_installation_id'), 'stretches', ['installation_id'], unique=False)
    op.add_column(
        "installations",
        sa.Column(
            "bronde_total",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
    )

    op.alter_column(
        "installations",
        "bronde_total",
        server_default=None,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('installations', 'bronde_total')
    op.drop_index(op.f('ix_stretches_installation_id'), table_name='stretches')
    op.drop_index('ix_stretches_from_to_brond', table_name='stretches')
    op.drop_table('stretches')
    op.drop_table('installation_progress')
    # ### end Alembic commands ###
