"""add project constraints

Revision ID: 454eae8e28c8
Revises: 079d0dec83f7
Create Date: 2026-09-10 12:35:56.107235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '454eae8e28c8'
down_revision: Union[str, Sequence[str], None] = '079d0dec83f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_constraints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=50), nullable=False),
    sa.Column('constraint_type', sa.String(length=50), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'constraint_type', 'reference', name='uq_project_constraints_project_type_reference')
    )
    op.create_index(op.f('ix_project_constraints_constraint_type'), 'project_constraints', ['constraint_type'], unique=False)
    op.create_index(op.f('ix_project_constraints_end_date'), 'project_constraints', ['end_date'], unique=False)
    op.create_index('ix_project_constraints_project_end_date', 'project_constraints', ['project_id', 'end_date'], unique=False)
    op.create_index(op.f('ix_project_constraints_project_id'), 'project_constraints', ['project_id'], unique=False)
    op.create_index('ix_project_constraints_project_type', 'project_constraints', ['project_id', 'constraint_type'], unique=False)
    op.create_index(op.f('ix_project_constraints_source_reference'), 'project_constraints', ['source_reference'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_constraints_source_reference'), table_name='project_constraints')
    op.drop_index('ix_project_constraints_project_type', table_name='project_constraints')
    op.drop_index(op.f('ix_project_constraints_project_id'), table_name='project_constraints')
    op.drop_index('ix_project_constraints_project_end_date', table_name='project_constraints')
    op.drop_index(op.f('ix_project_constraints_end_date'), table_name='project_constraints')
    op.drop_index(op.f('ix_project_constraints_constraint_type'), table_name='project_constraints')
    op.drop_table('project_constraints')
    # ### end Alembic commands ###
