"""Create project task foundation

Revision ID: 4cd07d00310a
Revises: 303082f2b692
Create Date: 2026-08-04 09:42:33.360330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4cd07d00310a'
down_revision: Union[str, Sequence[str], None] = '303082f2b692'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('customer', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=200), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('planned_completion_date', sa.Date(), nullable=True),
    sa.Column('actual_start_date', sa.Date(), nullable=True),
    sa.Column('actual_completion_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_table('task_types',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('standard_sequence', sa.Integer(), nullable=True),
    sa.Column('default_unit', sa.String(length=50), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('installations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=50), nullable=False),
    sa.Column('installation_no', sa.String(length=50), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('hoveddato', sa.Date(), nullable=True),
    sa.Column('expected_stik', sa.Integer(), nullable=False),
    sa.Column('active_stik', sa.Integer(), nullable=False),
    sa.Column('opened_stik', sa.Integer(), nullable=False),
    sa.Column('langhatte', sa.Integer(), nullable=False),
    sa.Column('korthatte_extra', sa.Integer(), nullable=False),
    sa.Column('broende', sa.Integer(), nullable=False),
    sa.Column('hovedledning_meter', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'installation_no', name='uq_installations_project_installation_no'),
    sa.UniqueConstraint('project_id', 'sequence', name='uq_installations_project_sequence')
    )
    op.create_index(op.f('ix_installations_hoveddato'), 'installations', ['hoveddato'], unique=False)
    op.create_index(op.f('ix_installations_project_id'), 'installations', ['project_id'], unique=False)
    op.create_table('project_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=50), nullable=False),
    sa.Column('installation_id', sa.Integer(), nullable=True),
    sa.Column('task_type_id', sa.String(length=50), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('scheduling_mode', sa.String(length=30), nullable=False),
    sa.Column('fixed_start_date', sa.Date(), nullable=True),
    sa.Column('earliest_start_date', sa.Date(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['installation_id'], ['installations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_type_id'], ['task_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('installation_id', 'task_type_id', name='uq_project_tasks_installation_task_type')
    )
    op.create_index(op.f('ix_project_tasks_deadline'), 'project_tasks', ['deadline'], unique=False)
    op.create_index(op.f('ix_project_tasks_installation_id'), 'project_tasks', ['installation_id'], unique=False)
    op.create_index(op.f('ix_project_tasks_project_id'), 'project_tasks', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_tasks_status'), 'project_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_project_tasks_task_type_id'), 'project_tasks', ['task_type_id'], unique=False)
    op.create_table('task_quantities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_task_id', sa.Integer(), nullable=False),
    sa.Column('quantity_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_task_id'], ['project_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_task_id', 'quantity_type', name='uq_task_quantities_task_quantity_type')
    )
    op.create_index(op.f('ix_task_quantities_project_task_id'), 'task_quantities', ['project_task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_quantities_project_task_id'), table_name='task_quantities')
    op.drop_table('task_quantities')
    op.drop_index(op.f('ix_project_tasks_task_type_id'), table_name='project_tasks')
    op.drop_index(op.f('ix_project_tasks_status'), table_name='project_tasks')
    op.drop_index(op.f('ix_project_tasks_project_id'), table_name='project_tasks')
    op.drop_index(op.f('ix_project_tasks_installation_id'), table_name='project_tasks')
    op.drop_index(op.f('ix_project_tasks_deadline'), table_name='project_tasks')
    op.drop_table('project_tasks')
    op.drop_index(op.f('ix_installations_project_id'), table_name='installations')
    op.drop_index(op.f('ix_installations_hoveddato'), table_name='installations')
    op.drop_table('installations')
    op.drop_table('task_types')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
