"""add project managers

Revision ID: 629c7c97ccd7
Revises: 72d5a76e68d8
Create Date: 2026-09-01 15:27:20.784599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '629c7c97ccd7'
down_revision: Union[str, Sequence[str], None] = '72d5a76e68d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "projects",
        sa.Column(
            "project_manager",
            sa.String(length=200),
            nullable=False,
            server_default="",
        ),
    )

    op.add_column(
        "projects",
        sa.Column(
            "site_manager",
            sa.String(length=200),
            nullable=False,
            server_default="",
        ),
    )

    op.alter_column(
        "projects",
        "project_manager",
        server_default=None,
    )

    op.alter_column(
        "projects",
        "site_manager",
        server_default=None,
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'site_manager')
    op.drop_column('projects', 'project_manager')
    # ### end Alembic commands ###
