"""add technical asset models

Revision ID: 72d5a76e68d8
Revises: fd3f9bc96200
Create Date: 2026-08-06 15:50:55.021640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '72d5a76e68d8'
down_revision: Union[str, Sequence[str], None] = 'fd3f9bc96200'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manholes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=50), nullable=False),
    sa.Column('manhole_no', sa.String(length=100), nullable=False),
    sa.Column('diameter_m', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('depth_m', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('profile', sa.String(length=100), nullable=False),
    sa.Column('material', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('depth_m IS NULL OR depth_m >= 0', name='ck_manholes_depth_non_negative'),
    sa.CheckConstraint('diameter_m IS NULL OR diameter_m >= 0', name='ck_manholes_diameter_non_negative'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'manhole_no', name='uq_manholes_project_manhole_no')
    )
    op.create_index(op.f('ix_manholes_active'), 'manholes', ['active'], unique=False)
    op.create_index('ix_manholes_project_active', 'manholes', ['project_id', 'active'], unique=False)
    op.create_index(op.f('ix_manholes_project_id'), 'manholes', ['project_id'], unique=False)
    op.create_table('manhole_work',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('manhole_id', sa.Integer(), nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=True),
    sa.Column('supersedes_work_id', sa.Integer(), nullable=True),
    sa.Column('work_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('performed_date', sa.Date(), nullable=True),
    sa.Column('performed_by', sa.String(length=150), nullable=True),
    sa.Column('team_id', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity >= 0', name='ck_manhole_work_quantity_non_negative'),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['manhole_id'], ['manholes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supersedes_work_id'], ['manhole_work.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manhole_work_decision_id'), 'manhole_work', ['decision_id'], unique=False)
    op.create_index(op.f('ix_manhole_work_manhole_id'), 'manhole_work', ['manhole_id'], unique=False)
    op.create_index('ix_manhole_work_performed_date', 'manhole_work', ['performed_date'], unique=False)
    op.create_index(op.f('ix_manhole_work_source_reference'), 'manhole_work', ['source_reference'], unique=False)
    op.create_index(op.f('ix_manhole_work_status'), 'manhole_work', ['status'], unique=False)
    op.create_index(op.f('ix_manhole_work_supersedes_work_id'), 'manhole_work', ['supersedes_work_id'], unique=False)
    op.create_index(op.f('ix_manhole_work_team_id'), 'manhole_work', ['team_id'], unique=False)
    op.create_index('ix_manhole_work_type_status', 'manhole_work', ['work_type', 'status'], unique=False)
    op.create_index(op.f('ix_manhole_work_work_type'), 'manhole_work', ['work_type'], unique=False)
    op.create_table('service_connections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stretch_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('position_m', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('clock_position', sa.String(length=20), nullable=False),
    sa.Column('dimension_mm', sa.Integer(), nullable=True),
    sa.Column('material', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('to_be_opened', sa.Boolean(), nullable=False),
    sa.Column('decommissioned', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('dimension_mm IS NULL OR dimension_mm > 0', name='ck_service_connections_dimension_positive'),
    sa.CheckConstraint('position_m >= 0', name='ck_service_connections_position_non_negative'),
    sa.ForeignKeyConstraint(['stretch_id'], ['stretches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stretch_id', 'external_id', name='uq_service_connections_stretch_external_id'),
    sa.UniqueConstraint('stretch_id', 'position_m', 'clock_position', name='uq_service_connections_stretch_position_clock')
    )
    op.create_index(op.f('ix_service_connections_active'), 'service_connections', ['active'], unique=False)
    op.create_index(op.f('ix_service_connections_decommissioned'), 'service_connections', ['decommissioned'], unique=False)
    op.create_index('ix_service_connections_status', 'service_connections', ['active', 'to_be_opened', 'decommissioned'], unique=False)
    op.create_index(op.f('ix_service_connections_stretch_id'), 'service_connections', ['stretch_id'], unique=False)
    op.create_index(op.f('ix_service_connections_to_be_opened'), 'service_connections', ['to_be_opened'], unique=False)
    op.create_table('service_connection_work',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_connection_id', sa.Integer(), nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=True),
    sa.Column('supersedes_work_id', sa.Integer(), nullable=True),
    sa.Column('work_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('performed_date', sa.Date(), nullable=True),
    sa.Column('performed_by', sa.String(length=150), nullable=True),
    sa.Column('team_id', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity >= 0', name='ck_service_connection_work_quantity_non_negative'),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_connection_id'], ['service_connections.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supersedes_work_id'], ['service_connection_work.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_connection_work_decision_id'), 'service_connection_work', ['decision_id'], unique=False)
    op.create_index('ix_service_connection_work_performed_date', 'service_connection_work', ['performed_date'], unique=False)
    op.create_index(op.f('ix_service_connection_work_service_connection_id'), 'service_connection_work', ['service_connection_id'], unique=False)
    op.create_index(op.f('ix_service_connection_work_source_reference'), 'service_connection_work', ['source_reference'], unique=False)
    op.create_index(op.f('ix_service_connection_work_status'), 'service_connection_work', ['status'], unique=False)
    op.create_index(op.f('ix_service_connection_work_supersedes_work_id'), 'service_connection_work', ['supersedes_work_id'], unique=False)
    op.create_index(op.f('ix_service_connection_work_team_id'), 'service_connection_work', ['team_id'], unique=False)
    op.create_index('ix_service_connection_work_type_status', 'service_connection_work', ['work_type', 'status'], unique=False)
    op.create_index(op.f('ix_service_connection_work_work_type'), 'service_connection_work', ['work_type'], unique=False)
    op.add_column('stretches', sa.Column('bottom_manhole_id', sa.Integer(), nullable=True))
    op.add_column('stretches', sa.Column('top_manhole_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_stretches_bottom_manhole_id'), 'stretches', ['bottom_manhole_id'], unique=False)
    op.create_index(op.f('ix_stretches_top_manhole_id'), 'stretches', ['top_manhole_id'], unique=False)
    op.create_foreign_key(
        "fk_stretches_bottom_manhole_id_manholes",
        "stretches",
        "manholes",
        ["bottom_manhole_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        "fk_stretches_top_manhole_id_manholes",
        "stretches",
        "manholes",
        ["top_manhole_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_stretches_top_manhole_id_manholes",
        "stretches",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_stretches_bottom_manhole_id_manholes",
        "stretches",
        type_="foreignkey",
    )
    op.drop_index(op.f('ix_stretches_top_manhole_id'), table_name='stretches')
    op.drop_index(op.f('ix_stretches_bottom_manhole_id'), table_name='stretches')
    op.drop_column('stretches', 'top_manhole_id')
    op.drop_column('stretches', 'bottom_manhole_id')
    op.drop_index(op.f('ix_service_connection_work_work_type'), table_name='service_connection_work')
    op.drop_index('ix_service_connection_work_type_status', table_name='service_connection_work')
    op.drop_index(op.f('ix_service_connection_work_team_id'), table_name='service_connection_work')
    op.drop_index(op.f('ix_service_connection_work_supersedes_work_id'), table_name='service_connection_work')
    op.drop_index(op.f('ix_service_connection_work_status'), table_name='service_connection_work')
    op.drop_index(op.f('ix_service_connection_work_source_reference'), table_name='service_connection_work')
    op.drop_index(op.f('ix_service_connection_work_service_connection_id'), table_name='service_connection_work')
    op.drop_index('ix_service_connection_work_performed_date', table_name='service_connection_work')
    op.drop_index(op.f('ix_service_connection_work_decision_id'), table_name='service_connection_work')
    op.drop_table('service_connection_work')
    op.drop_index(op.f('ix_service_connections_to_be_opened'), table_name='service_connections')
    op.drop_index(op.f('ix_service_connections_stretch_id'), table_name='service_connections')
    op.drop_index('ix_service_connections_status', table_name='service_connections')
    op.drop_index(op.f('ix_service_connections_decommissioned'), table_name='service_connections')
    op.drop_index(op.f('ix_service_connections_active'), table_name='service_connections')
    op.drop_table('service_connections')
    op.drop_index(op.f('ix_manhole_work_work_type'), table_name='manhole_work')
    op.drop_index('ix_manhole_work_type_status', table_name='manhole_work')
    op.drop_index(op.f('ix_manhole_work_team_id'), table_name='manhole_work')
    op.drop_index(op.f('ix_manhole_work_supersedes_work_id'), table_name='manhole_work')
    op.drop_index(op.f('ix_manhole_work_status'), table_name='manhole_work')
    op.drop_index(op.f('ix_manhole_work_source_reference'), table_name='manhole_work')
    op.drop_index('ix_manhole_work_performed_date', table_name='manhole_work')
    op.drop_index(op.f('ix_manhole_work_manhole_id'), table_name='manhole_work')
    op.drop_index(op.f('ix_manhole_work_decision_id'), table_name='manhole_work')
    op.drop_table('manhole_work')
    op.drop_index(op.f('ix_manholes_project_id'), table_name='manholes')
    op.drop_index('ix_manholes_project_active', table_name='manholes')
    op.drop_index(op.f('ix_manholes_active'), table_name='manholes')
    op.drop_table('manholes')
    # ### end Alembic commands ###
