"""Tilføj VPManhole billedregistrering

Revision ID: b818d5aa88bf
Revises: f6f3aa51daf4
Create Date: 2026-10-08 07:37:24.575939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b818d5aa88bf'
down_revision: Union[str, Sequence[str], None] = 'f6f3aa51daf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vpmanhole_deliveries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('manhole_id', sa.Integer(), nullable=False),
    sa.Column('folder_installation_id', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['completed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['folder_installation_id'], ['installations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['manhole_id'], ['manholes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('manhole_id', name='uq_vpmanhole_deliveries_manhole')
    )
    op.create_index(op.f('ix_vpmanhole_deliveries_manhole_id'), 'vpmanhole_deliveries', ['manhole_id'], unique=False)
    op.create_table('vpmanhole_photos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('delivery_id', sa.Integer(), nullable=False),
    sa.Column('photo_type', sa.String(length=20), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('relative_path', sa.String(length=1000), nullable=False),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(photo_type = 'during') OR (sequence = 1)", name='ck_vpmanhole_photos_single_sequence'),
    sa.CheckConstraint("photo_type IN ('before', 'during', 'after', 'cover')", name='ck_vpmanhole_photos_type'),
    sa.CheckConstraint('sequence >= 1', name='ck_vpmanhole_photos_sequence'),
    sa.ForeignKeyConstraint(['delivery_id'], ['vpmanhole_deliveries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('delivery_id', 'photo_type', 'sequence', name='uq_vpmanhole_photos_slot')
    )
    op.create_index(op.f('ix_vpmanhole_photos_delivery_id'), 'vpmanhole_photos', ['delivery_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vpmanhole_photos_delivery_id'), table_name='vpmanhole_photos')
    op.drop_table('vpmanhole_photos')
    op.drop_index(op.f('ix_vpmanhole_deliveries_manhole_id'), table_name='vpmanhole_deliveries')
    op.drop_table('vpmanhole_deliveries')
    # ### end Alembic commands ###
