"""Create teams calendars and assignments.

Revision ID: d64ff2356fa4
Revises: 4cd07d00310a
Create Date: 2026-08-04 10:44:42.373108
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "d64ff2356fa4"
down_revision: Union[str, Sequence[str], None] = "4cd07d00310a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "work_calendars",
        sa.Column(
            "id",
            sa.String(length=50),
            nullable=False,
        ),
        sa.Column(
            "name",
            sa.String(length=100),
            nullable=False,
        ),
        sa.Column(
            "timezone_name",
            sa.String(length=50),
            nullable=False,
        ),
        sa.Column(
            "active",
            sa.Boolean(),
            nullable=False,
        ),
        sa.Column(
            "notes",
            sa.Text(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "teams",
        sa.Column(
            "id",
            sa.String(length=50),
            nullable=False,
        ),
        sa.Column(
            "name",
            sa.String(length=100),
            nullable=False,
        ),
        sa.Column(
            "role",
            sa.String(length=50),
            nullable=False,
        ),
        sa.Column(
            "calendar_id",
            sa.String(length=50),
            nullable=True,
        ),
        sa.Column(
            "active",
            sa.Boolean(),
            nullable=False,
        ),
        sa.Column(
            "notes",
            sa.Text(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["calendar_id"],
            ["work_calendars.id"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(
        op.f("ix_teams_active"),
        "teams",
        ["active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_teams_calendar_id"),
        "teams",
        ["calendar_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_teams_role"),
        "teams",
        ["role"],
        unique=False,
    )

    op.create_table(
        "work_calendar_rules",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "calendar_id",
            sa.String(length=50),
            nullable=False,
        ),
        sa.Column(
            "weekday",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "working",
            sa.Boolean(),
            nullable=False,
        ),
        sa.Column(
            "start_time",
            sa.Time(),
            nullable=True,
        ),
        sa.Column(
            "end_time",
            sa.Time(),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["calendar_id"],
            ["work_calendars.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "calendar_id",
            "weekday",
            name="uq_work_calendar_rules_calendar_weekday",
        ),
    )

    op.create_index(
        op.f("ix_work_calendar_rules_calendar_id"),
        "work_calendar_rules",
        ["calendar_id"],
        unique=False,
    )

    op.create_table(
        "calendar_exceptions",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "calendar_id",
            sa.String(length=50),
            nullable=True,
        ),
        sa.Column(
            "team_id",
            sa.String(length=50),
            nullable=True,
        ),
        sa.Column(
            "date_from",
            sa.Date(),
            nullable=False,
        ),
        sa.Column(
            "date_to",
            sa.Date(),
            nullable=False,
        ),
        sa.Column(
            "exception_type",
            sa.String(length=50),
            nullable=False,
        ),
        sa.Column(
            "working",
            sa.Boolean(),
            nullable=False,
        ),
        sa.Column(
            "start_time",
            sa.Time(),
            nullable=True,
        ),
        sa.Column(
            "end_time",
            sa.Time(),
            nullable=True,
        ),
        sa.Column(
            "reason",
            sa.Text(),
            nullable=False,
        ),
        sa.Column(
            "decision_id",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "active",
            sa.Boolean(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["calendar_id"],
            ["work_calendars.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(
        op.f("ix_calendar_exceptions_calendar_id"),
        "calendar_exceptions",
        ["calendar_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_calendar_exceptions_date_from"),
        "calendar_exceptions",
        ["date_from"],
        unique=False,
    )
    op.create_index(
        op.f("ix_calendar_exceptions_date_to"),
        "calendar_exceptions",
        ["date_to"],
        unique=False,
    )
    op.create_index(
        op.f("ix_calendar_exceptions_team_id"),
        "calendar_exceptions",
        ["team_id"],
        unique=False,
    )

    op.create_table(
        "team_capacity_rates",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "team_id",
            sa.String(length=50),
            nullable=False,
        ),
        sa.Column(
            "task_type_id",
            sa.String(length=50),
            nullable=False,
        ),
        sa.Column(
            "quantity_type",
            sa.String(length=50),
            nullable=False,
        ),
        sa.Column(
            "capacity_per_day",
            sa.Float(),
            nullable=False,
        ),
        sa.Column(
            "unit",
            sa.String(length=30),
            nullable=False,
        ),
        sa.Column(
            "valid_from",
            sa.Date(),
            nullable=True,
        ),
        sa.Column(
            "valid_to",
            sa.Date(),
            nullable=True,
        ),
        sa.Column(
            "active",
            sa.Boolean(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["task_type_id"],
            ["task_types.id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "team_id",
            "task_type_id",
            "quantity_type",
            name="uq_team_capacity_rates_team_task_quantity",
        ),
    )

    op.create_index(
        op.f("ix_team_capacity_rates_task_type_id"),
        "team_capacity_rates",
        ["task_type_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_team_capacity_rates_team_id"),
        "team_capacity_rates",
        ["team_id"],
        unique=False,
    )

    op.create_table(
        "team_task_permissions",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "team_id",
            sa.String(length=50),
            nullable=False,
        ),
        sa.Column(
            "task_type_id",
            sa.String(length=50),
            nullable=False,
        ),
        sa.Column(
            "active",
            sa.Boolean(),
            nullable=False,
        ),
        sa.Column(
            "valid_from",
            sa.Date(),
            nullable=True,
        ),
        sa.Column(
            "valid_to",
            sa.Date(),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["task_type_id"],
            ["task_types.id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "team_id",
            "task_type_id",
            name="uq_team_task_permissions_team_task_type",
        ),
    )

    op.create_index(
        op.f("ix_team_task_permissions_task_type_id"),
        "team_task_permissions",
        ["task_type_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_team_task_permissions_team_id"),
        "team_task_permissions",
        ["team_id"],
        unique=False,
    )

    op.create_table(
        "task_assignments",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "project_task_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "team_id",
            sa.String(length=50),
            nullable=False,
        ),
        sa.Column(
            "active",
            sa.Boolean(),
            nullable=False,
        ),
        sa.Column(
            "valid_from",
            sa.Date(),
            nullable=True,
        ),
        sa.Column(
            "valid_to",
            sa.Date(),
            nullable=True,
        ),
        sa.Column(
            "assigned_by",
            sa.String(length=150),
            nullable=True,
        ),
        sa.Column(
            "source",
            sa.String(length=50),
            nullable=False,
        ),
        sa.Column(
            "reason",
            sa.Text(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_task_id"],
            ["project_tasks.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(
        "uq_task_assignments_task_team_valid_from",
        "task_assignments",
        [
            "project_task_id",
            "team_id",
            "valid_from",
        ],
        unique=True,
        postgresql_nulls_not_distinct=True,
    )
    op.create_index(
        op.f("ix_task_assignments_active"),
        "task_assignments",
        ["active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_task_assignments_project_task_id"),
        "task_assignments",
        ["project_task_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_task_assignments_team_id"),
        "task_assignments",
        ["team_id"],
        unique=False,
    )


def downgrade() -> None:
    op.drop_index(
        op.f("ix_task_assignments_team_id"),
        table_name="task_assignments",
    )
    op.drop_index(
        op.f("ix_task_assignments_project_task_id"),
        table_name="task_assignments",
    )
    op.drop_index(
        op.f("ix_task_assignments_active"),
        table_name="task_assignments",
    )
    op.drop_index(
        "uq_task_assignments_task_team_valid_from",
        table_name="task_assignments",
    )
    op.drop_table("task_assignments")

    op.drop_index(
        op.f("ix_team_task_permissions_team_id"),
        table_name="team_task_permissions",
    )
    op.drop_index(
        op.f("ix_team_task_permissions_task_type_id"),
        table_name="team_task_permissions",
    )
    op.drop_table("team_task_permissions")

    op.drop_index(
        op.f("ix_team_capacity_rates_team_id"),
        table_name="team_capacity_rates",
    )
    op.drop_index(
        op.f("ix_team_capacity_rates_task_type_id"),
        table_name="team_capacity_rates",
    )
    op.drop_table("team_capacity_rates")

    op.drop_index(
        op.f("ix_calendar_exceptions_team_id"),
        table_name="calendar_exceptions",
    )
    op.drop_index(
        op.f("ix_calendar_exceptions_date_to"),
        table_name="calendar_exceptions",
    )
    op.drop_index(
        op.f("ix_calendar_exceptions_date_from"),
        table_name="calendar_exceptions",
    )
    op.drop_index(
        op.f("ix_calendar_exceptions_calendar_id"),
        table_name="calendar_exceptions",
    )
    op.drop_table("calendar_exceptions")

    op.drop_index(
        op.f("ix_work_calendar_rules_calendar_id"),
        table_name="work_calendar_rules",
    )
    op.drop_table("work_calendar_rules")

    op.drop_index(
        op.f("ix_teams_role"),
        table_name="teams",
    )
    op.drop_index(
        op.f("ix_teams_calendar_id"),
        table_name="teams",
    )
    op.drop_index(
        op.f("ix_teams_active"),
        table_name="teams",
    )
    op.drop_table("teams")

    op.drop_table("work_calendars")