"""add stretch survey data

Revision ID: f6f3aa51daf4
Revises: 29cfa8bbda05
Create Date: 2026-10-07 08:09:11.087471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f6f3aa51daf4'
down_revision: Union[str, Sequence[str], None] = '29cfa8bbda05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stretch_surveys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stretch_id', sa.Integer(), nullable=False),
    sa.Column('existing_profile', sa.String(length=50), nullable=False),
    sa.Column('existing_dimension', sa.String(length=50), nullable=False),
    sa.Column('existing_material', sa.String(length=50), nullable=False),
    sa.Column('existing_length_m', sa.Float(), nullable=True),
    sa.Column('planned_dimension', sa.String(length=50), nullable=False),
    sa.Column('planned_length_m', sa.Float(), nullable=True),
    sa.Column('traffic', sa.String(length=50), nullable=False),
    sa.Column('bottom_cannot_open', sa.Boolean(), nullable=False),
    sa.Column('bottom_profile', sa.String(length=50), nullable=False),
    sa.Column('bottom_dimension_a_mm', sa.Float(), nullable=True),
    sa.Column('bottom_dimension_b_mm', sa.Float(), nullable=True),
    sa.Column('bottom_material', sa.String(length=50), nullable=False),
    sa.Column('top_cannot_open', sa.Boolean(), nullable=False),
    sa.Column('top_profile', sa.String(length=50), nullable=False),
    sa.Column('top_dimension_a_mm', sa.Float(), nullable=True),
    sa.Column('top_dimension_b_mm', sa.Float(), nullable=True),
    sa.Column('top_material', sa.String(length=50), nullable=False),
    sa.Column('measured_by', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['stretch_id'], ['stretches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stretch_surveys_stretch_id'), 'stretch_surveys', ['stretch_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stretch_surveys_stretch_id'), table_name='stretch_surveys')
    op.drop_table('stretch_surveys')
    # ### end Alembic commands ###
